# Change these first
owner: ThomasConrad # Your GitHub organization or username, where this repository lives
repo: uptime_monitor # The name of this repository

sites:
  - name: Cond.dk
    url: https://www.cond.dk
  - name: Plex
    url: https://plex.cond.dk/web/
  - name: Qbit
    url: https://qbit.cond.dk
  - name: Vaultwarden
    url: https://warden.cond.dk
  - name: Nextcloud
    url: https://files.cond.dk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cond.dk
  #baseUrl: /uptime_monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: My websites and services uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
